apiVersion: benchflow.io/v1alpha1
kind: DeploymentProfile
metadata:
  name: llm-d-pd-disaggregation-ibmcluster
spec:
  platform: llm-d
  mode: pd-disaggregation
  repo_url: /home/thibrahi/workspace/llm-d/llm-d
  repo_ref: main
  gateway: istio
  endpoint_path: /v1/models
  model_storage:
    pvc_name: models-storage
    cache_dir: /models
    mount_path: /model-cache
  runtime:
    replicas: 4
    tensor_parallelism: 4
    vllm_args:
      - --block-size=128
      - --kv-transfer-config={"kv_connector":"NixlConnector","kv_role":"kv_both"}
      - --max-model-len=32000
      - --disable-uvicorn-access-log
  prefill:
    replicas: 16
    tensor_parallelism: 1
    vllm_args:
      - --block-size=128
      - --kv-transfer-config={"kv_connector":"NixlConnector","kv_role":"kv_both"}
      - --max-model-len=32000
      - --disable-uvicorn-access-log
  options:
    guide_dirname: pd-disaggregation/tarball-extract/pd-disaggregation-deployment-ibmcluster-with-webhook
    model_values_relpath: ms-pd/values_ibmcluster.yaml
    scheduler_values_relpath: gaie-pd/values.yaml
    helmfile_environment: ibmcluster
    raw_helmfile_values: true
    pd_threshold: 0
    hash_block_size: 5
    enable_rdma: true
